Tc5
vladstrazhnikov/starbucks-cypress pull request #11
Opened 2022-05-31 15:06 UTC by vladstrazhnikov

2022-05-31 16:44 UTC, KirylParkhomenka requested changes

2022-05-31 16:44 UTC, KirylParkhomenka commented on cypress/integration/TestCase5.spec.js
> +        cy.get(menuPage.trentaRadiobutton).check('Trenta', { force: true })
1. What is the purpose of specifying 'Trenta' in `check()` method?
2. Remove `{ force: true }`
3. To specify element, which will not be covered, use xpath
4. Actually it's not a visible radiobutton for user. I'd better call it 'sizeOption'

2022-05-31 16:44 UTC, KirylParkhomenka commented on cypress/pages/MenuPage.js
> +    addBrownSugarSyropButton = '//div/div[1]/*[@class="stepper___1KL9Q"]//button[@class="quantityButton___7uYkS"]'
Awful locator. Possible to make it shorter.

2022-05-31 16:44 UTC, KirylParkhomenka commented on cypress/integration/TestCase5.spec.js
> +        cy.get(menuPage.appleJuiceSelect).select('Light Apple Juice')
Please store these options in testData

2022-05-31 16:44 UTC, KirylParkhomenka commented on cypress/integration/TestCase5.spec.js
> +        cy.get(menuPage.flavorsButton).contains('1 pump(s) Brown Sugar Syrup')
Assertions in Cypress are performed using '[should](https://docs.cypress.io/api/commands/should#Syntax)'.
Need to replace `contains` with `should` everywhere.
Explanation why - you can find [here](https://stackoverflow.com/questions/50042670/cypress-test-is-contains-equivalent-to-shouldcontain).

2022-05-31 17:32 UTC, vladstrazhnikov commented on cypress/integration/TestCase5.spec.js
> +        cy.get(menuPage.trentaRadiobutton).check('Trenta', { force: true })
As I understand I should replace trentaRadiobutton =  '#Trenta' with sizeOption =  '//*[@id="Trenta"]'?
And I tried different locator but without  { force: true } it does'n work
![image](https://user-images.githubusercontent.com/73987333/171237067-952a8715-abbb-4e80-8586-f42846da790a.png)

2022-06-01 08:20 UTC, KirylParkhomenka requested changes

2022-06-01 08:20 UTC, KirylParkhomenka commented on cypress/integration/TestCase5.spec.js
> +        cy.get(menuPage.trentaRadiobutton).should('be.checked')
Line 24 and 26 - radiobutton again?

2022-06-01 08:20 UTC, KirylParkhomenka commented on cypress/pages/MenuPage.js
> +    trentaRadiobutton = '#Trenta'
Line 4 and 5 - selectors will be almost the same, but with small difference

2022-06-02 10:04 UTC, KirylParkhomenka commented on cypress/pages/MenuPage.js
> +    trentaRadiobutton = '#Trenta'
Ok, use this one, but rename it

2022-06-02 10:07 UTC, vladstrazhnikov commented on cypress/pages/MenuPage.js
> +    trentaRadiobutton = '#Trenta'
or I can make something like '//*[@data-e2e="size-selector"]//*[@id="Trenta"]'
trentaItem is okay?

2022-06-02 10:13 UTC, KirylParkhomenka commented on cypress/pages/MenuPage.js
> +    trentaRadiobutton = '#Trenta'
no need, nothing will change

2022-06-02 16:25 UTC, KirylParkhomenka approved these changes

2022-06-02 16:53 UTC, merged