Test Case 1: Impossible to Sign up with empty fields
vladstrazhnikov/starbucks-cypress pull request #7
Opened 2022-05-19 17:07 UTC by vladstrazhnikov

2022-05-19 18:22 UTC, KirylParkhomenka requested changes

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/pages/MainPage.js
> +        cy.visit(this.baseURL)
Don't pass direct url here.
You should pass url in test.
Here just use a parameter, without specific value.

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        cy.title()
cy.get(el)

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        // Click on "Join now" button
It's a good practice to use `console.log('Text')` instead of comments.
You will see all logs in test output, but you will not see comments.

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        // Click on "Join now" button
Click "Join now" button, without 'on'.

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        cy.get(mainPage.joinBtnElem)
Please write it in a single line, it will be readable fine in a single line

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +            .should('be.visible')
No need to check visibility, it's an extra, not necessary step.
If element will not be visible, then Cypress will not click it.

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        cy.title()
No need to check it. Also please delete from TC.

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        // how to check rgb without borders?
You did it in line 30

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        cy.get(createAccountPage.firstNameElem).parent()
cy.get().should(); - in 1 line please

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        // What is another way to get div?
Another way is ti create a unique selector for <div> element

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +            .should('be.focused')
Why do you need to check focus??

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        // Validation messages
cy.log()

2022-05-19 18:22 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        for (let validationMessage of createAccountPage.validationMessages) {
I believe that you can work with arrays :)
But in current case it's a bad idea.
Each error for each field should be created as a separate constant.
The reason is next:

If there will be a bug, and error text for the FirstName input will be displayed instead of the error text for LastName input.
In this case will your test fail? The answer is - NO.

2022-05-21 00:09 UTC, vladstrazhnikov commented on cypress/starbucks/TestCase1.spec.js
> +        // Click on "Join now" button
cy.log() or console.log()?
Don't understand what's the point of using console.log()

2022-05-21 00:16 UTC, vladstrazhnikov commented on cypress/starbucks/TestCase1.spec.js
> +            .should('be.focused')
First name input field becomes focused after clicking Submit button, so I decided to test it

2022-05-21 06:41 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +            .should('be.focused')
Got it, ok then.

2022-05-21 06:43 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        // Click on "Join now" button
Sure, you need to use `cy.log()` I updated the comment.
I'm working with playwright now, where `console.log()` is used, so just mixed up them.

2022-05-23 09:31 UTC, KirylParkhomenka requested changes

2022-05-23 09:31 UTC, KirylParkhomenka commented on cypress/pages/CreateAccountPage.js
> +    createAccountButton = '.sb-frap'
Better to use 'data-test' attributes or similar, because current class is  not reliable.

2022-05-23 09:31 UTC, KirylParkhomenka commented on cypress/pages/MainPage.js
> +    //a[3][contains(text(),"Join now")]
Why do we need commented lines 2 and 3?

2022-05-23 09:31 UTC, KirylParkhomenka commented on cypress/pages/MainPage.js
> +    joinButton = '//a[3][contains(text(),"Join now")]'
Don't create selectors, which are relying on text, because your tests can  be used in other locales and specified test will be translated.
In current case you can use part of url.

2022-05-23 09:31 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        mainPage.openPage(urls.baseUrl)
There is no sense to create a separate method, which contains only 1 action.
You just created additional 3 lines of code, which actually can be replaced with `cy.visit(urls.baseUrl)`.

2022-05-23 09:31 UTC, KirylParkhomenka commented on cypress/testData/colours.json
> +{
Why json???
Create constant and store it in regular .js file

2022-05-23 09:31 UTC, KirylParkhomenka commented on cypress/testData/colours.json
> +{
Please also apply to other testData files.

2022-05-23 09:31 UTC, KirylParkhomenka commented on cypress/starbucks/TestCase1.spec.js
> +        cy.get(createAccountPage.firstNameValidationHint).contains(validationMessages.createAccountPageMessages.firstNameValidationHint).should('be.visible')
To long expression.
You need to store such test data in regular js file.
Your line  32 should look like:
`cy.get(createAccountPage.firstNameValidationHint).contains(validationMessages.firstNameValidationHint).should('be.visible')`

2022-05-23 11:58 UTC, KirylParkhomenka approved these changes

2022-05-23 13:18 UTC, merged